-- CREATE TABLE users (
--     id SERIAL NOT NULL PRIMARY KEY,
--     name VARCHAR(50) NOT NULL,
--     username VARCHAR(50) NOT NULL UNIQUE,
--     password TEXT NOT NULL,
--     pfp TEXT NOT NULL DEFAULT 'https://i.imgur.com/igF2kHr.png',
--     friends INTEGER[] NOT NULL DEFAULT '{}'::int[],
--     active BOOLEAN
-- );

-- CREATE TABLE messages (
--     id SERIAL NOT NULL PRIMARY KEY,
--     sender_id SERIAL NOT NULL REFERENCES users(id),
--     receiver_id SERIAL NOT NULL REFERENCES users(id),
--     content TEXT NOT NULL,
--     time_stamp TIMESTAMP NOT NULL DEFAULT now(),
--     read BOOLEAN
-- );

-- INSERT INTO users (name, username, password, active) VALUES('tester1', 'test', 'test', true);
-- INSERT INTO users (name, username, password, active) VALUES('tester2', 'test2', 'test2', true);
